<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FarLibCL\FarLibCL.csproj" />
    <ProjectReference Include="..\FarLibDAL\FarLibDAL.csproj" />
  </ItemGroup>

</Project>
